sudo: false
language: python

python:
    - "2.7"
    - "3.4"
    - "3.5"

env:
    - TOXENV=django18
    - TOXENV=django19

install:
    - "pip install -r requirements.txt"

script: "tox -e $TOXENV"
